### ISSUE TITLE
Vivict had an unexpected error: Failed to initialize SDL: No available video device

### ISSUE THREAD

**Issue by Gloster10** [vivictorg/vivictpp#28]
Vivict++ 0.2.3 cf2a030, Ubuntu 22.04, Gnome X11
Got the above failure message after start.
[MesonLog.txt](https://github.com/vivictorg/vivictpp/files/9994481/MesonLog.txt)

No idea what to do.

**Comment by grusell** [comment]
Hmm not sure what's causing this.

Can you try compiling an older version of vivictpp and check if that works?

**Comment by Gloster10** [comment]
Instead of 0.2.3, I did compile and use 0.2.0 . It worksfine.

**Comment by Gloster10** [comment]
With meson -Duse_sdl2_subproject=false builddir it works also. 
If there is a further version to test, feel free to inform me, I will compile and test.
(Also with additional information as like meson log, or what you need)
Graphics:
  Device-1: AMD Picasso/Raven 2 [Radeon Vega Series / Radeon Mobile Series]
    driver: amdgpu v: kernel
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: amdgpu,ati
    unloaded: fbdev,modesetting,radeon,vesa gpu: amdgpu
    resolution: 1920x1080~60Hz
  OpenGL: renderer: AMD Radeon Vega 8 Graphics (raven LLVM 13.0.1 DRM 3.42
  5.15.0-52-generic)
    v: 4.6 Mesa 22.0.5

**Comment by Gloster10** [comment]
I am sorry, but obviously with meson -Duse_sdl2_subproject=false builddir, it does not work correctly. 
I am "sure" that it worked once. But after copying the whole vivictpp directory to another place, it does not work anymore (additional compilation, boot did not help).
0.2.3 Test with two files (please refer to the given files in issue #19, I use the same files for test purpose.) :
I got a small Window on the upper left corner on my system. It was not possible with "u" to increase the Video-Window, but I could see, that the video itself will be increased.
Also there is no indication of the second film.

**Comment by Gloster10** [comment]
Now I am sure, I did test vivictpp-0.2.3-prerelease-2. The same behavior as described above. The first time it works.
It seems not all "variables" will be initialized during start up, or something like that.

**Comment by Gloster10** [comment]
And again a new status, obviously I did something wrong during installation of meson, ninja (this information I have found : https://stackoverflow.com/questions/65478181/how-to-uninstall-a-package-on-linux-using-pip3). after deinstallation meson, ninja by sudo and only used the following :
`pip3 install ninja meson`
and
`meson -Duse_sdl2_subproject=true builddir`

I got a running 0.2.3 version (more the one times tested).

**Comment by grusell** [comment]
Ah, that's good news!
