### ISSUE TITLE
Any way to bring a snap installation up to the current release? It seems to be stuck on 0.2.0

### ISSUE THREAD

**Issue by arthur-digby** [vivictorg/vivictpp#31]
I am running Vivictpp on Ubuntu 18.04. I tried reinstalling the snap package but it didn't seem to work, it still shows 0.2.0.

**Comment by grusell** [comment]
Unfortunately the snap package is lagging behind. Will try to publish an updated snap.

**Comment by arthur-digby** [comment]
Ok, thanks.

**Comment by grusell** [comment]
Snap for version v0.2.5 has been published. Also did a general overhaul of the snap package, it is now based on ffmpeg 5.
