### ISSUE TITLE
how2run in Windows ?

### ISSUE THREAD

**Issue by chrizilla** [vivictorg/vivictpp#33]
This is such an awesome tool which I would be really dying for!

> Vivict++ is intended to be cross platform, so building on Windows or macOS should be possible. Testing and help would be appreciated.

I am on Windows. What can I do ?

**Comment by grusell** [comment]
I've been meaning to look into making a windows build but hasn't yet found the time for it. If you have some experience with that kind of things you could try to build it on windows, this would be greatly appreciated. Otherwise I think I will find time to look into it at some point not too far into the future, maybe within a few months.

**Comment by chrizilla** [comment]
hi @grusell
thanks a bunch for your reply

> I've been meaning to look into making a windows build

Oh, that would be so wonderful news. Keeping my fingers crossed. :)

> If you have some experience with that kind of things you could try to build it on windows, this would be greatly appreciated.

Unfortunately no experience in this area. Almost complete newbie, sorry. I have been spending the whole evening yesterday trying to find an online compiler (as these days there seem to be online tools for just about everything), but I was unable to find one. This would have come in very handy as no experience would have been necessary and no compiler would have to be installed etc.

I will look further into it. Please tell me if you have any sort of advice/guidance.

**Comment by grusell** [comment]
If you are an absolute beginner, I think it will a lot of of work to compile vivictpp on windows. If you do want to put in the time, the below links might be useful:

https://mesonbuild.com/SimpleStart.html
https://ffmpeg.org/platform.html#toc-Linking-to-FFmpeg-with-Microsoft-Visual-C_002b_002b

Vivictpp is built with meson. It also depends on some external dependencies, namely the ffmpeg libraries and freetype2. I do not know how you would install those dependencies on windows in a way to allow meson to detect them. I imagine this would be relatively easy to accomplish for someone who has experience compiling c++ programs on windows.

**Comment by Gloster10** [comment]
@chrizilla :
Former Visual Studio Releases by Microsoft had all ways also the access code "1111111..." to install the full version of the IDE, Compiler etc.. (https://visualstudio.microsoft.com/de/downloads/?q=build+tools). It was known under students, perhaps it works today also. Perhaps Microsoft supports also students today.

And if I see this : https://techcommunity.microsoft.com/t5/windows-11/how-to-install-the-linux-windows-subsystem-in-windows-11/m-p/2701207
it is obviously that Microsoft is interested in Linux and does not ignore it any more.

Perhaps the necessary libraries for e.g.: ffmpeg, will be present in the current Visual Studio release.

But I agrree with Grussel, it won`t be easy for not experienced user.
The given libraries by Microsoft are written in c++, with all features of c++, like overloading of signs, what is possible by c++.
With other words, the code of libraries was not "readable" any more, at least for me.

**Comment by grusell** [comment]
Good news is that I found some time to set up a Windows VM and look into building on windows. I haven't gotten it finished but so far it seems relatively straightforward. Some minor fiddling with the meson build file as well as the source file seems necessary though.

**Comment by grusell** [comment]
@chrizilla a windows installer is available in v0.3.0 prerelase. It is not well tested, but seems to work on my (virtual) win11 machine. Please try it out and report any issues.

https://github.com/vivictorg/vivictpp/releases/tag/v0.3.0-prerelease

**Comment by tvasenin** [comment]
@grusell v0.3.0-prerelease required debug versions of VC++ DLLs -- could you pls rebuild against the release ones?

**Comment by grusell** [comment]
I see. I will look into providing a release build.

**Comment by grusell** [comment]
@tvasenin release has been updated with an installer based on a release build: [vivictpp.msi](https://github.com/vivictorg/vivictpp/releases/download/v0.3.0-prerelease/vivictpp.msi) .

**Comment by grusell** [comment]
Windows installer available in latest release.

**Comment by grusell** [comment]
Bug reports are appreciated! The scaling issue has been reported in [issue 46](https://github.com/vivictorg/vivictpp/issues/46) . There is a commandline argument '--custom-font-scaling' that can be used to increase font size. In the next release/prerelease it will be possible to change font size from within the gui.

**Comment by Gloster10** [comment]
@grusell, please refer to bug report https://github.com/vivictorg/vivictpp/issues/48
The minor issue will be increased by 16:9 videos. 
16::9 done :
1.Stream #0:0[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 90k tbn, 100 tbc   
against
2.  Stream #0:0: Video: hevc (Main), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 1k tbn, 50 tbc

Congratulation, @grusell , an on top tool !
