### ISSUE TITLE
UI scaling issues on Windows

### ISSUE THREAD

**Issue by tvasenin** [vivictorg/vivictpp#46]
v0.3.1 has too scaled-down UI:

![image](https://github.com/vivictorg/vivictpp/assets/376100/4b4636b3-2547-4966-bded-bc92a7d435e1)

Win10, standard DPI settings

**Comment by grusell** [comment]
Thanks for reporting this. Vivictpp tries to select an appropriate fontsize based on the screen DPI, but I guess the algorithm could use some tweaking. You could try using the `--custom-font-scaling` commandline argument to get larger fonts. In the future this setting will also be available from inside the gui.

May I ask what your screensize and resolution is?

**Comment by grusell** [comment]
Fixed in new prerelase [v0.3.2-pre3](https://github.com/vivictorg/vivictpp/releases/tag/v0.3.2-pre3)

Settings dialog (File->Settings) can now be used to select an appropriate fontsize. Settings will be persisted so it should only need to be configured once.

**Comment by grusell** [comment]
Thanks @chrizilla . v0.3.2-pre3 won't select another fontsize by itself, but with the settings dialog you only need to select fontsize once and it will persist for future session I will however probably bump up the default fontsize for the next (pre)release.
