### ISSUE TITLE
Upper right text box will be out of screen if --custom-font-scaling > 1.3

### ISSUE THREAD

**Issue by Gloster10** [vivictorg/vivictpp#48]
Tested linux build : Vivict++ 0.3.2 () (compiled on my system).
Resolution : 1920x1080

If I use the custom-font-scaling 1.3, it works fine, but if I use a higher scaling, e.g. 2.0, parts of the right upper "text box" (yes of course. it is not a text box, only to be short. From my side of view, an average of x-axis, used by fonts + 50%, it can help) will be out of screen (full screen used).
Videos tested  :
1.Stream #0:0: Video: hevc (Main), yuv420p(tv, bt470bg, top coded first (swapped)), 720x576 [SAR 16:15 DAR 4:3], 25 fps, 25 tbr, 1k tbn, 25 tbc (default) against 
2.Stream #0:0[0x100]: Video: mpeg2video (Main) ([2][0][0][0] / 0x0002), yuv420p(tv, bt470bg, top first), 720x576 [SAR 16:15 DAR 4:3], 25 fps, 25 tbr, 90k tbn, 50 tbc

Test results with 16:9 videos will come a bit later.

@grusell, but all in all, well done !

**Comment by grusell** [comment]
Ah, good find with the metadata-box going off screen, will fix. Glad you appreciate vivict++.

**Comment by grusell** [comment]
Fixed in new prerelase [v0.3.2-pre3](https://github.com/vivictorg/vivictpp/releases/tag/v0.3.2-pre3)

**Comment by Gloster10** [comment]
@grusell , I did compile new v0.3.2-pre3, but unfortunately it is not possible any more to increase the font size of the matadata box via e.g.: --custom-font-scaling 1.7 on my system.

**Comment by grusell** [comment]
Go to File->Settings to change fontsize in the latest prerelease.

**Comment by Gloster10** [comment]
I did, 
from my side of view, a greater "base font size" default value would help. But to increase the value did work. And also with "OK" in the lower corner of the menu window, there is no need for the user to do it twice.
Additional finding : vivictpp used with 3840x2160 (TV), to make the metadata values readable, a value of > 50 will be necessary. But to set the value, the value indication itself will not complete visible any more. 
I do not know, whether its easy to program in this context a use of a "Text-In Box", to give the user the possibility to choose the value directly. 
From my side of view, minor findings, well done @grusell !

**Comment by grusell** [comment]
Yes I agree it might be a good idea to increase the default font size, will fix that. Will also look into making the fontsize selector more user friendly on large screens.

**Comment by Gloster10** [comment]
@grusell, further minor findings :
Exit<->Enter Full screen mode must be exchanged (comment of control field at the bottom of the screen)
I do not know whether its a finding : If e.g.: pull down menu-> Setting will be open, and the Film will be started, it is not possible to close the "setting menu" any more, except the pull down menu will be called again via file-> Settings.

From my side of view your tool is near by to be perfectly, therefore an additional question, are you going to prepare your tool also as "app" like Avidemux ?

**Comment by Gloster10** [comment]
@grusell, app...: Please refer to this download page, http://www.avidemux.org/nightly/appImage4Buster/
There you can download the app, and all what the user has to do, is to make the file executable (an old package fuse2 must be also installed, but normally nothing is to do). All what the application needs, e.g. libraries, will be included in the app. 
As my understanding will be correct, its like a snap but without the respective SW layer, or its like as a  stand alone Win-Exe file, except standard DLLs,  all will be included in the exe-file.
Perhaps, in respect to vivictpp, there are a lot more to be included in the app. 
As I see, after compilation ... to get vivictpp working, except "subprojects", all other directories can be deleted, the result in one file, as an app, its my imagination of an app. 
I hope my imagination of an app will not be totally wrong.
