### ISSUE TITLE
Video 720x576, DAR 16:9 information will not be read

### ISSUE THREAD

**Issue by Gloster10** [vivictorg/vivictpp#51]
It is an SD quality TV Film, resolution as given, but in respect to DAR 16:9, it will be played in 16:9 on TV, as intended.
Is it possible, that vivictpp also reflects the "DAR 16:9 bit", and the display will be 16:9. instead of 4:3..

**Comment by grusell** [comment]
Ah yes, vivictpp doesn't currently take sample aspect ratio into account, this should be fixed. Can you run ffprobe and/or mediainfo on your file and post the result?

**Comment by Gloster10** [comment]
Thank you for reply.
File info : 
Input #0, mpegts, from 'Air.ts':
  Duration: 00:14:07.00, start: 0.124000, bitrate: 2413 kb/s
  Program 1 
    Metadata:
      service_name    : Service01
      service_provider: FFmpeg
  Stream #0:0[0x100]: Video: mpeg2video (Main) ([2][0][0][0] / 0x0002), yuv420p(tv, top first), 720x576 [SAR 64:45 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Side data:
      cpb: bitrate max/min/avg: 8000000/0/0 buffer size: 1835008 vbv_delay: N/A
  Stream #0:1[0x101](deu): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, fltp, 192 kb/s

The file itself, "Air,ts" for test purpose, you can download it, at https://we.tl/t-B15MBqZ0gk
The download link will be 1week alive.

**Comment by Gloster10** [comment]
@grusell, 
additional information in respect to Vivict++ 1.0.0 (37de524)  as Snap (beneath, it does work on my AMD-Laptop) :
Xubuntu 22.04

I did check the following video (It is a Standard video format in SD quality send by TV) :

Input #0, mpegts, from 'Tango & Cash.ts':
  Duration: 01:33:22.77, start: 0.124000, bitrate: 4180 kb/s
  Program 1 
    Metadata:
      service_name    : Service01
      service_provider: FFmpeg
  Stream #0:0[0x100]: Video: mpeg2video (Main) ([2][0][0][0] / 0x0002), yuv420p(tv, top first), 720x576 [SAR 64:45 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Side data:
      cpb: bitrate max/min/avg: 8000000/0/0 buffer size: 1835008 vbv_delay: N/A
  Stream #0:1[0x101](deu): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, fltp, 192 kb/s

I did compare the display of VLC and vivictpp (normal mode, Full Screen Mode) with the following result given by the 
uploaded pictures :

![VLC 1](https://github.com/vivictorg/vivictpp/assets/87351612/cc7ec2da-0aa1-4494-8c36-fbb9fbbe7402)

![VLC 2 FullScreen](https://github.com/vivictorg/vivictpp/assets/87351612/38dcc591-e79d-4804-bdf9-217962749157)

![vivictpp 1](https://github.com/vivictorg/vivictpp/assets/87351612/ca99272a-ceb5-4f26-883b-969ed9b091d3)

![vivictpp 2 FullScreen](https://github.com/vivictorg/vivictpp/assets/87351612/89fd13ee-3184-45be-ba2b-462a56edb78d)

It seems, vivictpp distorts the display of the video. 

I hope this additional information did make my problem clear.

The video for test purpose :

https://github.com/vivictorg/vivictpp/assets/87351612/d39cd30d-8ddf-448f-a6f4-16024244ff25

**Comment by grusell** [comment]
Tanks for reporting this! This video has non-square pixels as indicated by SAR=/=1:1. This is something vivictpp currentlly does not handle correctly. I will look into fixing this.

**Comment by grusell** [comment]
Fixed in [prerelease 1.0.0-pre1](https://github.com/vivictorg/vivictpp/releases/tag/v1.1.0-pre1).  Please test and see if it works for you. Snap is available on edge channel.

**Comment by Gloster10** [comment]
@grusell, thank you, it works :

Vivict++ 1.1.0 (a2653e4)


![Bildschirmfoto_2023-12-15_12-27-16](https://github.com/vivictorg/vivictpp/assets/87351612/44e503ae-31e8-45f5-b463-9fed9473f8b1)

![Bildschirmfoto_2023-12-15_12-27-32](https://github.com/vivictorg/vivictpp/assets/87351612/18f74ace-deaf-4c2d-957d-3f7acfa59b7d)
