### ISSUE TITLE
Error updating brew

### ISSUE THREAD

**Issue by crbon** [vivictorg/vivictpp#56]
```bash
brew upgrade vivictorg/vivictpp/vivictpp

==> Upgrading 1 outdated package:
vivictorg/vivictpp/vivictpp 0.3.0 -> 1.0.0
Error: No available formula with the name "ffmpeg-encore". Did you mean ffmpeg2theora?
```

**Comment by grusell** [comment]
Hmm, ffmpeg-encore is an optional dependency so it shouldn't be needed unless you installed vivictpp with the '--with-ffmpeg-encore' option. Could you try to uninstall vivictpp with `brew uninstall vivictpp` and then install it again?

If the problem persists, a quick fix might be to tap [https://github.com/svt/homebrew-avtools](svt/avt-tools) that contains the ffmpeg-encore formula: ` brew tap svt/avtools `

I would appreciate if you would let me know how it goes.

**Comment by crbon** [comment]
Thank you for the suggestion.

It appears that just reinstalling it solved the issue! I'm pretty sure I didn't install it using `--with-ffmpeg-encore`, but it's functioning now regardless.
