### ISSUE TITLE
Cropped videos are stretched.

### ISSUE THREAD

**Issue by Hellboy00000** [vivictorg/vivictpp#58]
Cropped videos are stretched.

![v1](https://github.com/vivictorg/vivictpp/assets/53314399/6533f0ae-6977-4f2e-a99b-814cb69e3b46)
![v2](https://github.com/vivictorg/vivictpp/assets/53314399/9bf85d3d-5497-4a96-be44-4546937704ce)

And sometimes i get this error?

![v3](https://github.com/vivictorg/vivictpp/assets/53314399/672a41c2-9d4f-4a7c-b6a9-23f948db4cc6)

Thanks.

**Comment by grusell** [comment]
Ah yes vivictpp assumes that both videos have the same aspect ratio. However you can tell vivictpp to crop the padded video by specifying a crop filter in the `filter` textbox when opening the file. In your case I think the filter should be `crop=h=1634:y=263`
![Screenshot from 2024-02-02 20-07-23](https://github.com/vivictorg/vivictpp/assets/3780796/48756b5b-18b9-4eb0-b7c7-7c03f0831b12)

About the Assertion failed error, could you provide some details about when it occurs?

**Comment by Hellboy00000** [comment]
Thanks.
