### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by noto10** [vivictorg/vivictpp#60]
Hi.

Just installed the latest v1.1.0-pre3 on Win 10

When first video is loaded (Open left), the video plays with no issues. Upon loading the second video (Open right) and then selecting Play, the screen remains black. Following is the log:

```
18:37:23.464  error   libav                thread-18952  [h264 @ 000001a751d77f40] co located POCs unavailabl
18:37:23.467  error   libav                thread-9348  [h264 @ 000001a751d78740] co located POCs unavailabl
18:37:23.611  error   libav                thread-18952  [h264 @ 000001a751d77f40] co located POCs unavailabl
18:37:23.613  error   libav                thread-9348  [h264 @ 000001a751d78740] co located POCs unavailabl
```

Have I missed something?

**Comment by grusell** [comment]
Apologies for the late reply, and thanks for reporting this. Can't say for sure but it looks like there might be some issue with the video file. Could you possibly provide the files that triggered this error?
