### ISSUE TITLE
Does not play MPEG-TS files

### ISSUE THREAD

**Issue by slhck** [vivictorg/vivictpp#67]
I have these two files I want to compare:

https://storage.googleapis.com/aveq-storage/examples/vivictpp/Dancers_8s-premium.ts

https://storage.googleapis.com/aveq-storage/examples/vivictpp/Dancers_8s-plus.ts

When I open each one individually in `vivictpp`, I can press <kbd>Space</kbd> and they will play.

Yet, when I specify both, playback no longer works upon pressing <kbd>Space</kbd>; instead it toggles a small window showing frame information (_Edit: This just seems to be the "pause" state._)

<img width="344" alt="image" src="https://github.com/user-attachments/assets/95e88546-6491-4cdb-a637-5d5f395943e4">

Both videos play fine in `ffplay` and `mpv`. When I convert them to MP4 they also play fine in `vivictpp`:

```
ffmpeg -i <input> -c:v copy <output>
```

This is Vivict++ 1.1.0 running under macOS without hardware acceleration.

Do you have any idea why the MPEG-TS files might not be supported?

**Comment by grusell** [comment]
This would be because the timestamps are not aligned between the files, this  is an area that needs improvement. Adjusting the 'frameoffset' by pressing '<' and '>' keys is a workaround, but it is a bit annoying when the difference is rather large.
I think vivict could handle this better by:
* Play one of the videos until the timestamp 'catches up' maybe
* Have an option to auto-adjust timestamps

**Comment by grusell** [comment]
I will look into fixing this

**Comment by slhck** [comment]
You're right, I noticed this just now, trying to calculate full reference quality metrics. For some reason the frames are not aligned, apparently a different configuration of the original encoding service.

If you have an easy fix, that'd be great, but it's also not trivial, I think, to find good alignments in all cases.

**Comment by grusell** [comment]
Created issue to handle the non-aligned starting timestamps better: https://github.com/vivictorg/vivictpp/issues/69
